TRUNCATE TABLE audit_logs;

DELETE FROM decisions
WHERE decision_id != 0;

DELETE FROM tasks
WHERE task_id != 0;

DELETE FROM incidents
WHERE incident_id != 0;

DELETE FROM budgets
WHERE budget_id != 0;

DELETE FROM kpi_logs
WHERE kpi_id != 0;

DELETE FROM requests
WHERE request_id != 0;

DELETE FROM workflows
WHERE workflow_id != 0;

DELETE FROM workflow_stages
WHERE stage_id != 0;

UPDATE departments
SET manager_id = NULL
WHERE dept_id != 0;

DELETE FROM employees
WHERE emp_id != 0;

DELETE FROM departments
WHERE dept_id != 0;

DELETE FROM roles
WHERE role_id != 0;

ALTER TABLE kpi_logs MODIFY (kpi_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE roles MODIFY (role_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE departments MODIFY (dept_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE budgets MODIFY (budget_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE incidents MODIFY (incident_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE employees MODIFY (emp_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE requests MODIFY (request_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE decisions MODIFY (decision_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE tasks MODIFY (task_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE audit_logs MODIFY (audit_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE workflows MODIFY (workflow_id GENERATED ALWAYS AS IDENTITY (START WITH 1));
ALTER TABLE workflow_stages MODIFY (stage_id GENERATED ALWAYS AS IDENTITY (START WITH 1));

COMMIT;